cmake_minimum_required(VERSION 4.2)
project(estrutura_de_dados)

set(CMAKE_CXX_STANDARD 14)

add_executable(estrutura_de_dados
        .idea/.gitignore
        .idea/estrutura-de-dados.iml
        .idea/misc.xml
        .idea/modules.xml
        .idea/vcs.xml
        .idea/workspace.xml
        LICENSE
        README.md
        "Aula01 - Revisão Lógica de Programação/Exercicios/q01.c"
        "Aula01 - Revisão Lógica de Programação/Exercicios/q02.c"
        "Aula01 - Revisão Lógica de Programação/Exercicios/q03.c"
        "Aula01 - Revisão Lógica de Programação/Exercicios/q04.c")
