cmake_minimum_required(VERSION 4.2)
project(estrutura_de_dados)

set(CMAKE_CXX_STANDARD 14)

add_executable(estrutura_de_dados
        .idea/.gitignore
        .idea/estrutura-de-dados.iml
        .idea/misc.xml
        .idea/modules.xml
        .idea/vcs.xml
        .idea/workspace.xml
        LICENSE
        README.md
        "Aula01 - Revisão Lógica de Programação/Exercicios/001.c"
        "Aula01 - Revisão Lógica de Programação/Exercicios/002.c"
        "Aula01 - Revisão Lógica de Programação/Exercicios/003.c"
        "Aula01 - Revisão Lógica de Programação/Exercicios/004.c"
        "Aula01 - Revisão Lógica de Programação/Exercicios/005.c"
        "Aula01 - Revisão Lógica de Programação/Exercicios/006.c"
        "Aula01 - Revisão Lógica de Programação/Exercicios/007.c"
        "Aula01 - Revisão Lógica de Programação/Exercicios/008.c"
        "Aula01 - Revisão Lógica de Programação/Exercicios/009.c"
        "Aula01 - Revisão Lógica de Programação/Exercicios/010.c")
